default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: '1qaz'
  socket: /run/mysqld/mysqld.sock

development:
  <<: *default
  database: groupme_development

test:
  <<: *default
  database: groupme_test

production:
  <<: *default
  database: groupme_production
